[package]
name = "star-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
log = "0.4.20"
octocrab = "0.32.0"
shuttle-actix-web = "0.33.0"
shuttle-runtime = "0.33.0"
tokio = "1.26.0"
